### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by anoukaveresch** [sjelfull/craft3-http2serverpush#6]
Is there gonna be an update for craft 4 support?

**Comment by patrikalienus** [comment]
I would also like to see Craft 4 support for this plugin.

**Comment by sjelfull** [comment]
No plans for that, but happy to take PRs.

**Comment by patrikalienus** [comment]
Ok so in other words, the plugin is considered abandoned?

**Comment by sjelfull** [comment]
That is correct, yes.
